# Generated by Django 4.2.3 on 2024-07-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='team_name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
