# Generated by Django 4.2.3 on 2024-07-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_waitlist_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='team_name',
            field=models.CharField(max_length=200),
        ),
    ]
