# Generated by Django 4.2.3 on 2024-07-11 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_waitlist_team_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='waitList',
            new_name='registrations',
        ),
    ]
